/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iti-logo.glb
*/

import { useGSAP } from '@gsap/react';
import { useGLTF } from '@react-three/drei';
import gsap from 'gsap';
import { useRef } from 'react';

export function ITILogoModel(props) {
  const { nodes, materials } = useGLTF('/3d/iti-logo.glb');
  const logoRef = useRef(null);

  useGSAP(() => {
    gsap.from(logoRef.current.scale, {
      x: 0,
      y: 0,
      z: 0,
      duration: 1.5,
      ease: 'back.out',
    });
    gsap.from(logoRef.current.rotation, {
      y: -Math.PI / 3,
      duration: 1.5,
      ease: 'power3.out',
    });
    gsap.from(logoRef.current.position, {
      y: '+=0.2',
      duration: 1.5,

      repeat: -1,
      yoyo: true,
      ease: 'power1.inOut',
    });
  }, []);

  return (
    <group ref={logoRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.I_dot.geometry}
        material={materials['Material.002']}
        position={[-0.465, 0.828, -0.003]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.918}
      />
      <mesh
        geometry={nodes.T_head.geometry}
        material={materials['Material.002']}
        position={[0.117, 0.291, -0.008]}
      />
      <mesh
        geometry={nodes.I_letter.geometry}
        material={materials['Material.002']}
        position={[-0.465, 0.04, -0.006]}
      />
      <mesh
        geometry={nodes.T_letter.geometry}
        material={materials['Material.002']}
        position={[0.005, -0.209, -0.014]}
        scale={[1, 1, 0.881]}
      />
      <mesh
        geometry={nodes.i_letter.geometry}
        material={materials['Material.002']}
        position={[0.48, -0.748, -0.015]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/3d/iti-logo.glb');
