/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iti-logo.glb
*/

import { useGLTF } from '@react-three/drei';

export default function ITILogoModel(props) {
  const { nodes, materials } = useGLTF('/3d/iti-logo.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.I_dot.geometry}
        material={materials['Material.002']}
        position={[-0.465, 0.828, -0.003]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.918}
      />
      <mesh
        geometry={nodes.T_head.geometry}
        material={materials['Material.002']}
        position={[0.117, 0.291, -0.008]}
      />
      <mesh
        geometry={nodes.i_negative.geometry}
        material={materials['Material.002']}
        position={[0.454, 0.289, 0.111]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.918}
      />
      <mesh
        geometry={nodes.I_letter.geometry}
        material={materials['Material.002']}
        position={[-0.465, 0.04, -0.006]}
      />
      <mesh
        geometry={nodes.T_letter.geometry}
        material={materials['Material.002']}
        position={[0.005, -0.209, -0.014]}
        scale={[1, 1, 0.881]}
      />
      <mesh
        geometry={nodes.i_letter.geometry}
        material={materials['Material.002']}
        position={[0.48, -0.748, -0.015]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/3d/iti-logo.glb');
