/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 logo-base.glb
*/

import { useGLTF } from '@react-three/drei';

export function LogoBaseModel(props) {
  const { nodes, materials } = useGLTF('/3d/logo-base.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        position={[-0.138, -1.281, 0.168]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.531, -0.033, -1.531]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.003']}
        position={[-0.129, -1.254, 0.158]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.433, -0.031, -1.433]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.001']}
        position={[-0.116, -1.243, 0.141]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.283, -0.028, -1.283]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.004']}
        position={[-0.082, -1.201, 0.1]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.911, -0.02, -0.911]}
      />
    </group>
  );
}

useGLTF.preload('/3d/logo-base.glb');
